version: '2'
services:
  web:
    image: "dragontek/octobercms"
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/themes/take-theme
  mysql:
    image: "mariadb"
    environment:
     - MYSQL_ROOT_PASSWORD=example
  memcached:
    image: "memcached"
